# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OTBhZWM3MjY1NDhjYzExZGY4NDkxNTBmMTljOGM4M2FiNzlkOWFkMTAxY2JhYmQ4YjE2N2FiMzIxYzJlYmEzOGJlODY3Y2VlMDkyMzk3OGIwM2QyMmU5MmZmNzMyNjhkYzJmMDcwMzlhNzVkNGMxZWQyMmEyZTliMjEwZjYwYWY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
